env:
  contexts:
    - name: web-selenium-template
      urls:
        - https://app.captaincredit.co.il
        - https://srv.captaincredit.co.il
      includePaths:
        - https://srv.captaincredit.co.il.*
        - .*srv.captaincredit.co.il.*
      excludePaths:

    - name: spider-ajax
      urls:
        - https://app.captaincredit.co.il
        - https://srv.captaincredit.co.il
      includePaths:
        - https://assets.gist.build.*
        - https://engine-consumer-api.cloud.gist.build.*
        - https://code.gist.build.*
        - https://renderer.gist.build.*
        - https://api-js.mixpanel.com.*
        - https://stats.g.doubleclick.net.*
        - https://analytics.google.com.*
        - https://www.googletagmanager.com.*
        - https://cdp.customer.io.*
        - https://srv.captaincredit.co.il.*
        - https://firebase.googleapis.com.*
        - https://fonts.gstatic.com.*
        - https://connect.facebook.net.*
        - https://app.captaincredit.co.il.*
        - .*srv.captaincredit.co.il.*
        - .*frontegg.*
        - .*auth0.*
        - .*cognito.*
      excludePaths: []
  parameters:
    failOnError: true
    failOnWarning: false
    progressToStdout: true
  vars:
    api_domain: srv.captaincredit.co.il
    login_url: https://app.captaincredit.co.il/sign-in
    username: 0543154545
    username_selector: "input[type=tel]"
    password: Qq123456
    password_selector: "input[type=password]"

jobs:
  - type: script
    name: Add httpsender
    parameters:
      action: add
      type: httpsender
      engine: "ECMAScript : Oracle Nashorn"
      name: persistAuthentication.js
      file: "/zap/automationScripts/persistAuthentication.js"

  - type: import
    parameters:
      type: url
      fileName: "/zap/wrk/PREVIOUS_SCANNED_URLS.txt"

  - type: import
    parameters:
      type: url
      fileName: "/zap/wrk/jit-crawler/collected_domain_requests.txt"

  - type: script
    name: Add seleniumUserPasswordLogin
    parameters:
      action: add
      type: selenium
      engine: "ECMAScript : Oracle Nashorn"
      name: seleniumUserPasswordLogin.js
      file: "/zap/automationScripts/seleniumUserPasswordLogin.js"

  - type: script
    parameters:
      action: add
      type: standalone
      engine: "ECMAScript : Oracle Nashorn"
      name: printFoundURLs.js
      file: "/zap/automationScripts/printFoundURLs.js"

  - type: passiveScan-config
    parameters:
      maxBodySizeInBytesToScan: 2621440  # 2.5MB
      scanOnlyInScope: true
      disableAllRules: true
    rules:
    - id: 10038                  # Content Security Policy (CSP) Header Not Set
      threshold: "Medium"
    - id: 10108                  # Reverse Tabnabbing
      threshold: "Medium"
    - id: 10042                  # HTTPS to HTTP Insecure Transition in Form Post
      threshold: "Medium"
    - id: 10003                  # Vulnerable JS Library
      threshold: "Medium"
    - id: 10033                  # Directory Browsing
      threshold: "Medium"
    - id: 10041                  # HTTP to HTTPS Insecure Transition in Form Post
      threshold: "Medium"
    - id: 10035                  # Strict-Transport-Security Header
      threshold: "Medium"
    - id: 10028                  # Open Redirect
      threshold: "Medium"
    - id: 10055                  # CSP
      threshold: "Medium"
    - id: 10020                  # Anti-clickjacking Header
      threshold: "Medium"
    - id: 10109                  # Modern Web Application
      threshold: "Medium"
    - id: 90003                  # Sub Resource Integrity Attribute Missing
      threshold: "Medium"
    - id: 2                  # Private IP Disclosure
      threshold: "Off"
    - id: 3                  # Session ID in URL Rewrite
      threshold: "Off"
    - id: 10009                  # In Page Banner Information Leak
      threshold: "Off"
    - id: 10010                  # Cookie No HttpOnly Flag
      threshold: "Off"
    - id: 10011                  # Cookie Without Secure Flag
      threshold: "Off"
    - id: 10015                  # Re-examine Cache-control Directives
      threshold: "Off"
    - id: 10017                  # Cross-Domain JavaScript Source File Inclusion
      threshold: "Off"
    - id: 10019                  # Content-Type Header Missing
      threshold: "Off"
    - id: 10021                  # X-Content-Type-Options Header Missing
      threshold: "Off"
    - id: 10023                  # Information Disclosure - Debug Error Messages
      threshold: "Off"
    - id: 10024                  # Information Disclosure - Sensitive Information in URL
      threshold: "Off"
    - id: 10025                  # Information Disclosure - Sensitive Information in HTTP Referrer Header
      threshold: "Off"
    - id: 10026                  # HTTP Parameter Override
      threshold: "Off"
    - id: 10027                  # Information Disclosure - Suspicious Comments
      threshold: "Off"
    - id: 10029                  # Cookie Poisoning
      threshold: "Off"
    - id: 10030                  # User Controllable Charset
      threshold: "Off"
    - id: 10031                  # User Controllable HTML Element Attribute (Potential XSS)
      threshold: "Off"
    - id: 10032                  # Viewstate
      threshold: "Off"
    - id: 10034                  # Heartbleed OpenSSL Vulnerability (Indicative)
      threshold: "Off"
    - id: 10036                  # HTTP Server Response Header
      threshold: "Off"
    - id: 10037                  # Server Leaks Information via 'X-Powered-By' HTTP Response Header Field(s)
      threshold: "Off"
    - id: 10039                  # X-Backend-Server Header Information Leak
      threshold: "Off"
    - id: 10040                  # Secure Pages Include Mixed Content
      threshold: "Off"
    - id: 10043                  # User Controllable JavaScript Event (XSS)
      threshold: "Off"
    - id: 10044                  # Big Redirect Detected (Potential Sensitive Information Leak)
      threshold: "Off"
    - id: 10049                  # Content Cacheability
      threshold: "Off"
    - id: 10050                  # Retrieved from Cache
      threshold: "Off"
    - id: 10052                  # X-ChromeLogger-Data (XCOLD) Header Information Leak
      threshold: "Off"
    - id: 10054                  # Cookie without SameSite Attribute
      threshold: "Off"
    - id: 10056                  # X-Debug-Token Information Leak
      threshold: "Off"
    - id: 10057                  # Username Hash Found
      threshold: "Off"
    - id: 10061                  # X-AspNet-Version Response Header
      threshold: "Off"
    - id: 10062                  # PII Disclosure
      threshold: "Off"
    - id: 10063                  # Permissions Policy Header Not Set
      threshold: "Off"
    - id: 10096                  # Timestamp Disclosure
      threshold: "Off"
    - id: 10097                  # Hash Disclosure
      threshold: "Off"
    - id: 10098                  # Cross-Domain Misconfiguration
      threshold: "Off"
    - id: 10105                  # Weak Authentication Method
      threshold: "Off"
    - id: 10110                  # Dangerous JS Functions
      threshold: "Off"
    - id: 10202                  # Absence of Anti-CSRF Tokens
      threshold: "Off"
    - id: 90001                  # Insecure JSF ViewState
      threshold: "Off"
    - id: 90002                  # Java Serialization Object
      threshold: "Off"
    - id: 90011                  # Charset Mismatch
      threshold: "Off"
    - id: 90022                  # Application Error Disclosure
      threshold: "Off"
    - id: 90030                  # WSDL File Detection
      threshold: "Off"
    - id: 90033                  # Loosely Scoped Cookie
      threshold: "Off"
    - id: 10032                  # Potential IP Addresses Found in the Viewstate
      threshold: "Off"
    - id: 10032                  # Emails Found in the Viewstate
      threshold: "Off"
    - id: 10049                  # Non-Storable Content
      threshold: "Off"
    - id: 10049                  # Storable and Cacheable Content
      threshold: "Off"
    - id: 10063                  # Deprecated Feature Policy Header Set
      threshold: "Off"
    - id: 10105                  # Authentication Credentials Captured
      threshold: "Off"
    - id: 10054                  # Cookie with Invalid SameSite Attribute
      threshold: "Off"
    - id: 10054                  # Cookie with SameSite Attribute None
      threshold: "Off"
    - id: 10054                  # Cookie without SameSite Attribute
      threshold: "Off"
    - id: 10063                  # Permissions Policy Header Not Set
      threshold: "Off"
    - id: 3                  # Referer Exposes Session ID
      threshold: "Off"
    - id: 3                  # Session ID in URL Rewrite
      threshold: "Off"
    - id: 3                  # Session ID in URL Rewrite
      threshold: "Off"
    - id: 10105                  # Weak Authentication Method
      threshold: "Off"
    - id: 10094                  # ASP.NET ViewState Disclosure
      threshold: "Off"
    - id: 10094                  # ASP.NET ViewState Integrity
      threshold: "Off"
    - id: 10094                  # Base64 Disclosure
      threshold: "Off"
    - id: 10044                  # Big Redirect Detected (Potential Sensitive Information Leak)
      threshold: "Off"
    - id: 10044                  # Multiple HREFs Redirect Detected (Potential Sensitive Information Leak)
      threshold: "Off"
    - id: 10032                  # Old Asp.Net Version in Use
      threshold: "Off"
    - id: 10032                  # Split Viewstate in Use
      threshold: "Off"
    - id: 10032                  # Viewstate without MAC Signature (Sure)
      threshold: "Off"
    - id: 10032                  # Viewstate without MAC Signature (Unsure)
      threshold: "Off"
    - id: 10019                  # Content-Type Header Empty
      threshold: "Off"
    - id: 10019                  # Content-Type Header Missing
      threshold: "Off"
    - id: 110009                  # Full Path Disclosure
      threshold: "Off"
    - id: 10103                  # Image Exposes Location or Privacy Data
      threshold: "Off"
    - id: 10036                  # Server Leaks its Webserver Application via 'Server' HTTP Response Header Field
      threshold: "Off"
    - id: 10036                  # Server Leaks Version Information via 'Server' HTTP Response Header Field
      threshold: "Off"

  - type: passiveScan-wait
    parameters:
      maxDuration: 3

  - type: spiderAjax
    parameters:
      context: spider-ajax
      url: https://app.captaincredit.co.il
      maxDuration: 10
      numberOfBrowsers: 2
      clickDefaultElems: false
      elements:
        - "a"
        - "button"
        - "div"
        - "input"
        - "label"
        - "li"
        - "ul"
        - "span"
        - "h1"
        - "h2"
        - "h3"
        - "p"
        - "td"
        - "th"
        - "tr"
        - "select"
        - "nav"
        - "img"
        - "ol"
        - "radio"
        - "section"
        - "option"

  - type: delay
    parameters:
      time: 1

  - type: passiveScan-wait
    parameters:
      maxDuration: 1

  - type: spider
    parameters:
      context: web-selenium-template
      maxDuration: 2

  - type: delay
    parameters:
      time: 3

  - type: script
    parameters:
      action: run
      type: standalone
      name: printFoundURLs.js
  - type: delay
    parameters:
      time: 1

  - type: activeScan
    parameters:
      maxScanDurationInMins: 12
      context: web-selenium-template
    policyDefinition:
      defaultThreshold: "Off"

      rules:
      - id: 90034                  # Cloud Metadata Potentially Exposed
        threshold: "Medium"
      - id: 40012                  # Cross Site Scripting (Reflected)
        threshold: "Medium"
      - id: 90025                  # Expression Language Injection
        threshold: "Medium"
      - id: 20019                  # External Redirect
        threshold: "Medium"
      - id: 90024                  # Generic Padding Oracle
        threshold: "Medium"
      - id: 6                  # Path Traversal
        threshold: "Medium"
      - id: 10048                  # Remote Code Execution - Shell Shock
        threshold: "Medium"
      - id: 7                  # Remote File Inclusion
        threshold: "Medium"
      - id: 90020                  # Remote OS Command Injection
        threshold: "Medium"
      - id: 90019                  # Server Side Code Injection
        threshold: "Medium"
      - id: 40009                  # Server Side Include
        threshold: "Medium"
      - id: 10045                  # Source Code Disclosure - /WEB-INF folder
        threshold: "Medium"
      - id: 20017                  # Source Code Disclosure - CVE-2012-1823
        threshold: "Medium"
      - id: 43                  # Source Code Disclosure - File Inclusion
        threshold: "Medium"
      - id: 41                  # Source Code Disclosure - Git 
        threshold: "Medium"
      - id: 42                  # Source Code Disclosure - SVN
        threshold: "Medium"
      - id: 40018                  # SQL Injection
        threshold: "Medium"
      - id: 90023                  # XML External Entity Attack
        threshold: "Medium"

  - type: report
    name: "Generate JSON report"
    parameters:
      template: traditional-json-plus
      reportDir: /zap/wrk
      reportFile: "zap_report.json"
    risks:
      - high
      - medium
    confidences:
      - high
      - medium

  - type: report
    name: "Generate PDF report"
    parameters:
      template: "traditional-pdf"
      reportDir: "/zap/wrk/public"
      reportFile: "zap_report.pdf"
      reportTitle: "Web Scan Security Report"
    risks:
      - high
      - medium
    confidences:
      - high
      - medium
    sites:
      - "https://app.captaincredit.co.il"
      - "srv.captaincredit.co.il"

  - type: script
    name: Add standaloneLogStatistics
    parameters:
      action: add
      type: standalone
      engine: "ECMAScript : Oracle Nashorn"
      name: standaloneLogStatistics.js
      file: "/zap/automationScripts/standaloneLogStatistics.js"

  - type: script
    name: "Run standaloneLogStatistics"
    parameters:
      action: run
      type: standalone
      name: standaloneLogStatistics.js