rules:
  - id: custom-rule-poc
    patterns:
      - pattern-either:
        - pattern: ai_hackathon_fn()
        - pattern: catch_this_func()
    message: |
      Custom Semgrep rule to identify snippets to POC custom rules of the AI Hackathon
    severity: ERROR
    languages:
      - python